### ISSUE TITLE
Names for Mx Commands and Options

### ISSUE THREAD

**Issue by mrigger** [graalvm/sulong#16]
The [Sulong mx commands ](https://github.com/graalvm/sulong/blob/f9aef9d0aaf70eec0333ca06861fb32c8a92f62a/mx.sulong/mx_sulong.py) use a lowercase command prefixed by **su-** and (inconsistently) using **-** as a word delimiter. Examples are **su-run** and **su-tests-gcc**.

The [Sulong options](https://github.com/graalvm/sulong/blob/f9aef9d0aaf70eec0333ca06861fb32c8a92f62a/projects/com.oracle.truffle.llvm.runtime/src/com/oracle/truffle/llvm/runtime/LLVMOptions.java) are currently implemented by System options prefixed by **llvm-**. They also use **-** as word delimiter. Examples are **llvm-opt-valueprofiling** and **llvm-print-asts**.

A typical command on the command line looks (for me) like this:  **mx su-run -Dgraal.Dump=Truffle -Dllvm-print-asts=true test.ll**.

Since the naming should change as infrequently as possible, it would be good to make a permanent decision about the naming conventions.

**Comment by mrigger** [comment]
For the mx command, I would like to emit the prefix. The above commands **su-run** and **su-tests-gcc** could then be, for example, changed to **sulong** and **tests-gcc**. One drawback is that the Sulong and other mx commands are shuffled together, and it is harder to locate a command that belongs to Sulong. It would be great to have a grouping function in mx, where all the commands of a suite belong to one category.

For the  System properties it would be good to be consistent with Graal and use **sulong.** as prefix. The above properties **llvm-opt-valueprofiling** and **llvm-print-asts** could then, e.g., be **sulong.OptValueProfiling** and **sulong.LLVMPrintASTs**.

The command line from above would then change to this:  **mx sulong -Dgraal.Dump=Truffle -sulong.LLVMPrintASTs=true test.ll**.

**Comment by chrisseaton** [comment]
That all makes sense to me.

Do you want me to actually implement that, since you've assigned to me? Happy do that if you do.

**Comment by mrigger** [comment]
Sorry, assigning this to you was an accident.

**Comment by dougxc** [comment]
We could add support for prefixing a command with its suite name:

```mx sulong:run ...```

All the commands with their suite prefix could be displayed by `mx -v`.

@cosminbasca may have other thoughts on this related to major mx refactoring his is working on.
