### ISSUE TITLE
On Stack Replacement

### ISSUE THREAD

**Issue by mrigger** [graalvm/sulong#19]
Sulong does not implement On Stack Replacement (OSR). Since Sulong cannot directly reuse the [LoopNode](https://github.com/graalvm/truffle/blob/c6886343eeaa0c98c0869491189e3c57a005bae0/truffle/com.oracle.truffle.api/src/com/oracle/truffle/api/nodes/LoopNode.java) provided by the Truffle framework, we have to implement our own version of it.

**Comment by grimmerm** [comment]
We won't add OSR anytime soon.
