### ISSUE TITLE
Make failures of unsupported instructions lazy

### ISSUE THREAD

**Issue by mrigger** [graalvm/sulong#191]
Currently, the parser throws exceptions for unsupported LLVM IR instructions. This prevents execution of larger libraries, where functions with unsupported instructions might never be executed. To partially support these libraries, we have to make the failures lazy, i.e., throw an exception in a node and not in the parser.

**Comment by grimmerm** [comment]
Please open a specific issue for missing instructions - we want to improve completeness and not crash lazily ;-)
