### ISSUE TITLE
Automatically install external dependencies such as gcc-4.6

### ISSUE THREAD

**Issue by mrigger** [graalvm/sulong#21]
Currently, the Sulong [mx commands](https://github.com/graalvm/sulong/blob/92a3f4326cbd1b7cdd6e0219978ba008dba6c4e8/mx.sulong/mx_sulong.py) assume that some external programs such as gcc-4.6 are already installed on the machine (see [here](https://github.com/graalvm/sulong/blob/92a3f4326cbd1b7cdd6e0219978ba008dba6c4e8/UBUNTU.md)). Instead, the mx script should automatically install these, if they are not installed yet. For that, it could simply use the system's package manager such as apt-get or yum on Linux.

**Comment by mickjordan** [comment]
Doesn't that require sudo privileges?

**Comment by mrigger** [comment]
Yes, it does. Probably it's a bad idea to ask for sudo rights in a script.

As an alternative, we could check if the dependencies are installed and on the path. If they are not, we could download them. However, that would make things more complicated since we also have to consider that the standard libraries paths have to be included when compiling.

Maybe we just exit the mx script and notify the user on which libraries he/she should install?
