### ISSUE TITLE
Support for 80 bit floats in native calls

### ISSUE THREAD

**Issue by mrigger** [graalvm/sulong#22]
Currently, Sulong does not provide native interoperability for [80 bit floats](http://llvm.org/docs/LangRef.html#floating-point-types). The Graal Native Function Interface (NFI) does not handle them, since there are no 80 bit float primitives in Java. Probably, we have to extend the NFI to correctly handle passing and alignment of them.

**Comment by grimmerm** [comment]
We are not using the Graal Native Function Interface anymore.
