### ISSUE TITLE
Fix Arithmetic Operations for 80 Bit Floats

### ISSUE THREAD

**Issue by mrigger** [graalvm/sulong#24]
Sulong implements 80 bit floating point numbers in a class [LLVM80BitFloat](https://github.com/graalvm/sulong/blob/db830610d6ffbdab9678eef359a9f915e6ad2ee8/projects/com.oracle.truffle.llvm.types/src/com/oracle/truffle/llvm/types/floating/LLVM80BitFloat.java) since Java itself does not provide them.

Still, arithmetic operations such as subtraction, addition, multiplication, remainder, and division are implemented using double precision. Besides fixing them to use 80 bit float precision, it would be good for performance to somehow treat them special during compilation.

**Comment by mrigger** [comment]
Should we move the 80 bit float class to Truffle? Then we could have method substitutions in Graal to intrinsify the arithmetic operations and map them directly to x87 instructions.

It is quite complex to implement the arithmetic operations 100% correctly in Java. Maybe we can omit having the Java implementation and directly produce machine code which we then call?

/cc @rschatz @christianwimmer

**Comment by rschatz** [comment]
Not every CPU supports 80 bit float. That actually makes me wonder, what does the SPARC llvm backend produce if some code uses long double? Perhaps we can do the same...

Also, we need to have a fallback implementation for the interpreter.

**Comment by mrigger** [comment]
Yes, it depends on the architecture for which you are compiling.

Consider the following function:

```
long double test() {
	return 1;
}
```

If I compile the function using Clang for my x86 machine I get the following:

```
target triple = "x86_64-pc-linux-gnu"
define x86_fp80 @test() #0 {
  ret x86_fp80 0xK3FFF8000000000000000
}

```
If I cross-compile the function to SPARC with `-target sparcv9` then I get the following:

```
target triple = "sparcv9"

define double @test() #0 {
  ret double 1.000000e+00
}
```
Where the architecture supports 80 bit floats Clang uses them to represent long doubles, otherwise Clang just outputs 64 bit floats. There is also a section about the different implementations on [Wikipedia](https://en.wikipedia.org/wiki/Long_double#Implementations). Representing long doubles with either 80 bit floats or 64 bit floats is conform with C and C++, since the languages do not enforce a certain bit width for data types, just the relationships between them.
