### ISSUE TITLE
Document installation procedure for Ubuntu 16.04

### ISSUE THREAD

**Issue by nirvdrum** [graalvm/sulong#258]
The README currently has instructions for installation on Ubuntu, but they don't work for the latest 16.04 LTS release. In particular gcc-4.6 isn't available in Ubuntu 16.04. There is likely a way to use the older packages from the the previous LTS release (14.04) or perhaps a PPA. To make installation easier, it'd be helpful to have a document set of steps on how to do so.

**Comment by chrisseaton** [comment]
We should also make it more clear that you don't need GCC at all unless you want to run Sulong tests or do something with Fortran. Some users such as Ruby only need the clang tarball which Sulong downloads as a binary for you.

**Comment by mrigger** [comment]
@lxp: You installed `gcc-4.6` on Ubuntu 16.04, right? Could you document how you achieved this?

@chrisseaton I agree. I think we should also adapt the test suite to only execute the GCC test cases if GCC is installed. Then, we could use Travis' build matrix feature to execute the tests with and without GCC.

**Comment by lxp** [comment]
My solution is not really perfect. I just added the old trusty repositories and set the default release to xenial, so that only selected packages or packages not existing in xenial are used from trusty.

Add trusty repository: (You might want to use a different mirror)
```
$ echo 'deb http://at.archive.ubuntu.com/ubuntu/ trusty main universe
deb http://at.archive.ubuntu.com/ubuntu/ trusty-updates main universe
deb http://security.ubuntu.com/ubuntu trusty-security main universe' | sudo tee /etc/apt/sources.list.d/trusty.list
```
Set the default release:
```
$ echo 'APT::Default-Release "xenial";' | sudo tee /etc/apt/apt.conf.d/20defaultrelease
```

Updated package lists and install dependencies:
```
$ sudo aptitude update
$ sudo aptitude install g++-4.6 gcc-4.6 gcc-4.6-plugin-dev gfortran-4.6 gobjc++-4.6 llvm-3.3 pylint/trusty python-astroid/trusty
```

**Comment by mrigger** [comment]
@lxp: I integrated your description into `DEPENDENCIES.md` (see #485).
