### ISSUE TITLE
Make LLVMNodes serializable

### ISSUE THREAD

**Issue by mrigger** [graalvm/sulong#281]
Since we started to add files that are loaded as dynamic libraries (in the `mx.sulong/libs` directory) start-up performance got worse since these files have to be loaded in addition to the main program. The situation will get worse if we substitute more functions of the standard library.

As a way to improve start-up performance we could let `LLVMNode` implement `Serializable` and store the (uninitialized) Truffle nodes on the disk. If the C files were not modified and the node implementations did not change we could load the Truffle nodes from the disk instead of having to run the parser to parse the bitcode file and create the Truffle ASTs.

We could also store the global symbols of each serialized file. With this information we would only have to load those shared library files that we actually need.

**Comment by grimmerm** [comment]
Startup and parsing performance was improved significantly. We won't go down the road of serializing LLVMNodes.
