### ISSUE TITLE
Graal Native Function Interface Performance Problem

### ISSUE THREAD

**Issue by mrigger** [graalvm/sulong#35]
Currently, native function calls are really slow. With the Graal Foreign Function Interface they should actually be very fast, since there should not be any overhead between the Truffle and native side, just the argument conversion and a direct call to the native side. [1]

Instead of being lowered to a call stub, the Graal graph contains a `CompilerToVM.executeInstalledCode` invoke node, even after the last compiler phase.

[1]  [An efficient native function interface for Java](http://dl.acm.org/citation.cfm?id=2500832)

**Comment by mrigger** [comment]
@rschatz currently works on this issue in https://github.com/graalvm/graal-core/pull/77.

**Comment by rschatz** [comment]
Should be fixed in #60.
