### ISSUE TITLE
Call sulong from simplelanguage

### ISSUE THREAD

**Issue by sidkshatriya** [graalvm/sulong#350]
I want to be able to use the polyglot feature of the Truffle API to be able to call sulong from, say, simplelanguage.

How would I go about doing this?

**Comment by sidkshatriya** [comment]
By simplelanguage I mean, of course, https://github.com/graalvm/simplelanguage

**Comment by chumer** [comment]
The Truffle way of calling into other languages from an existing Language is using
TruffleLanguage.Env#parse(Source). It will return a CallTarget that represents that function. The language is identified using the mime-type of the Source object.
This can be done using the SLContext, which stores TruffleLanguage.Env instance anywhere you want inside SimpleLanguage. If you want the enable the Truffle inliner to optimize across this boundary you need to wrap it into a DirectCallNode using DirectCallNode#create(CallTarget), embed it into the AST and call it.

I will let the Sulong people comment on potential specifics to their language.

**Comment by chrisseaton** [comment]
Interop with Sulong is complicated by the fact that it most people do not want to eval snippets of LLVM IR (which is what Sulong expects). When we use Sulong to run C extensions from JRuby, we eval the IR compiled from the C and then look up the C extension initialisation function, which has a known name, and execute that.

You may want to do something quite different, so it may be best to give us some pseudo code of the SL and C (or some other language?) that you want to run and how you imagine you'd like to write the interop code. Then we can help you shape that into something that works.

**Comment by chumer** [comment]
Oh I forgot. Another way of doing is by exporting a symbol in sulong and import it using TruffleLanguage.Env#importSymbol. If the symbol represents a function in Sulong and implements TruffleObject, we can call it using interop. SimpleLanguage supports to call foreign functions just as any other function. See SLDispatchNode#doForeign for details, how thats achieved.
