### ISSUE TITLE
Email address for security suggestion for sulong

### ISSUE THREAD

**Issue by sidkshatriya** [graalvm/sulong#351]
I have a small suggestion regarding sulong which is security related. Please don't be alarmed -- its its just a suggestion -- but I thought it might be better to communicate on email rather than post this as a ticket.

Can you give me an email address where I can email?

**Comment by chrisseaton** [comment]
I don't think we'd recommend anyone use Sulong in any production setting just yet. But you can email me chris.seaton@oracle.com if you want to.

**Comment by sidkshatriya** [comment]
Just sent you email -- thanks.
