### ISSUE TITLE
Fortran Benchmark Runner

### ISSUE THREAD

**Issue by mrigger** [graalvm/sulong#36]
Currently, the [mx commands](https://github.com/graalvm/sulong/blob/41db05a93eeedf4157314ab453f9f05420114245/mx.sulong/mx_sulong.py) provide functions to execute benchmarks with Sulong, GCC, and Clang. 

The commands still lack Fortran support. It is necessary to implement Fortran specific parts both in the GCC benchmark command and for Sulong.

**Comment by grimmerm** [comment]
That should not be part of mx.
