### ISSUE TITLE
Current Parser Limitations

### ISSUE THREAD

**Issue by mrigger** [graalvm/sulong#37]
Our current parser has three limitations:
1. The parser bases on the textual format of the LLVM IR which can change between minor versions. Our parser thus only supports LLVM IR versions 3.2-3.4.
2. The parser uses Xtext which is not easy to integrate in our mx tool. I tried to integrate it once but it seems that a few components in the parser depend on paths relative to the Eclipse project.
3. The parser is quite slow and memory hungry. It provides more features than we need, since it was originally used in an Eclipse LLVM IR editor.

I think that we should replace the current textual parser by a binary parser. With a binary parser, we would have stability guarantees for one major plus one minor version. We could also include the binary parser in our mx tool, since it presumably would not rely on external tools. A binary parser would also be faster.

**Comment by grimmerm** [comment]
https://github.com/graalvm/sulong/pull/603
