### ISSUE TITLE
Fix linking of extern variables

### ISSUE THREAD

**Issue by mrigger** [graalvm/sulong#380]
Currently, linking of extern symbols is broken when the external symbol is defined in one of the LLVM IR files (see #340). The current lookup logic (see `LLVMVisitor`) is as following:
```
if ("external".equals(linkage)) {
    long getNativeSymbol = nativeLookup.getNativeHandle(globalVarName);
    LLVMAddress nativeSymbolAddress = LLVMAddress.fromLong(getNativeSymbol);
    return factoryFacade.createLiteral(nativeSymbolAddress, LLVMBaseType.ADDRESS);
} else {
    Object findOrAllocateGlobal = findOrAllocateGlobal(globalVariable);
    assert findOrAllocateGlobal != null;
    return factoryFacade.createLiteral(findOrAllocateGlobal, LLVMBaseType.ADDRESS);
}
```
Per default, external symbols are looked up by using the Graal NFI while they should first be looked up in the bitcode files. 

It is not enough to add a condition that checks if there is already an entry for a global variable (`&& !globalVars.containsKey(globalVariable)`) since space for all global variables is initially allocated, even if the symbol is looked up later and the allocated global variable space not used. Even if the redundant allocation would be fixed inside the `LLVMVisitor` it would not be enough to find global extern variables that are defined in other files.

To fix this issue, we have to traverse all bitcode files, determine the unresolved extern variables and resolve them (with the Graal NFI). We could either keep patch addresses and patch them after constructing the ASTs (with one traversal) or first determine the unresolved global variables, and then construct the right references in the visitor (with two traversals).

**Comment by chrisseaton** [comment]
I wonder if our su-link tool could do any kind of useful pre-processing of the LLVM files? In this case it would mean you could have a file that listed all globals allocated in LLVM files, and you can read that before you read the LLVM files. It might let us do some other useful things.

**Comment by mrigger** [comment]
I think it does not pay off, since parsing will probably not be Sulong's bottleneck with the new parser.

**Comment by chrisseaton** [comment]
I'm not so sure - think about a huge library, from which you use just one routine. We could even store the location of each routine in the file and parse just that one routine on demand.

**Comment by mrigger** [comment]
Maybe we can wait until we have finished the integration of the bitcode parser, and then we can see if having such a table in the `.su` file improves performance?
