### ISSUE TITLE
Support converting managed objects to native

### ISSUE THREAD

**Issue by chrisseaton** [graalvm/sulong#402]
This pattern is common in Ruby:

```c
native_function(RSTRING_PTR(string));
```

Where `string` is a Ruby object, and `RSTRING_PTR` is a function that exposes the `char*` in it. We normally support this by returning another managed object that just provides the illusion of a `char*` but actually reads and writes the managed Ruby string.

This doesn't work when we want to pass the string to native.

I think an option here would be for Sulong to give Ruby the chance to convert the string to a native representation when it escapes to native. We could have a new interop message `NATIVE`, and it would work something like this:

Sulong sees a managed object being passed to a native function. It would pass it the `NATIVE` message. For the Ruby string object, this message would be implemented by calling `Unsafe.allocateMemory` and copying the managed string data into native memory, and then returning the pointer. Ruby already has multiple internal representations for strings, and this new native representation would just be another one of those. The Ruby program could keep running using the native string as normal. Ruby returns the address of this native memory from the `NATIVE` message, and Sulong passes that to the native function.

**Comment by grimmerm** [comment]
In general, I like the idea.
What I like most is that we can do that as late as possible, i.e., at the very last moment before the string escapes to native code. Some kind of worst case scenario. 

However, I think NATIVE message should not become part of the Truffle Interop API, this is too Sulong/Ruby specific. It is possible to create additional and specialized messages though.

**Comment by chrisseaton** [comment]
Yes we could do it via an `INVOKE` with a special name, and Sulong could know to send the message based on looking at the `ObjectType` to see it's a Ruby object.

**Comment by chrisseaton** [comment]
Having solved some other issues, this is now the thing that is blocking me and we can see where it needs to go.

```
Caused by: com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Unexpected values provided for LLVMAddressToI64NodeGen@1c4c5e0: [org.jruby.truffle.interop.cext.CExtString@6ffd08ac], [CExtString]
	at com.oracle.truffle.api.dsl.internal.SpecializationNode.unsupported(SpecializationNode.java:481)
	at com.oracle.truffle.api.dsl.internal.SpecializationNode.uninitialized(SpecializationNode.java:396)
	at com.oracle.truffle.llvm.nodes.impl.cast.LLVMToI64NodeFactory$LLVMAddressToI64NodeGen$UninitializedNode_.executeLong_(LLVMToI64NodeFactory.java:709)
	at com.oracle.truffle.llvm.nodes.impl.cast.LLVMToI64NodeFactory$LLVMAddressToI64NodeGen$BaseNode_.execute(LLVMToI64NodeFactory.java:667)
	at com.oracle.truffle.llvm.nodes.impl.cast.LLVMToI64NodeFactory$LLVMAddressToI64NodeGen.executeGeneric(LLVMToI64NodeFactory.java:603)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMCallNode$LLVMAbstractCallNode.evaluateArgs(LLVMCallNode.java:165)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMCallNode$LLVMResolvedDirectNativeCallNode.executeGeneric(LLVMCallNode.java:249)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMCallNode$LLVMUnresolvedCallNode.executeGeneric(LLVMCallNode.java:203)
	at com.oracle.truffle.llvm.nodes.impl.func.LLVMCallUnboxNodeFactory$LLVMI32CallUnboxNodeGen.executeI32(LLVMCallUnboxNodeFactory.java:188)
```

So an address escaping to native goes through `LLVMAddressToI64Node`. I wonder if we should have a separate node that is specifically for converting values to native so that we don't run this logic where we don't want it?

You can see here that the object we need to convert is a `CExtString`. That's JRuby+Truffle's object for strings that are pretending to be `char*`. At the moment it doesn't have any methods, so I'm going to experiment with adding one to do the conversion.

Here's a sticking point I could do with some big idea help on, @mrigger, I can call a method to do the conversion instead of adding a new message, but there's no way to see if the object will respond to that message ahead of time - no equivalent to `HAS_SIZE` etc. So how do I know if I should try calling my message conversion method?

Maybe I should just look for `CExtString` for now and special case it? It's quite urgent that we get on with this.

**Comment by mrigger** [comment]
Can we just have a `LLVMConvertToNative` node with specializations for all the input values that can come from Sulong, and one for `TruffleObject`? The `TruffleObject` can then call the conversion method, or use a newly introduced message to resolve the conversion.

What would also work is that you implement a `jruby-sulong` `NodeFactoryFacadeProvider` where you instantiate a new node facade that inherits from the current one, but where you override the behavior on how the conversion of objects should work when passing them to the native side. You could then specify with `sulong.NodeConfiguration=jruby-sulong` that this new factory facade should be used. To make this easier we could move `LLVMCallNode#convertToPrimitiveNode` to the node factory facade.

**Comment by mrigger** [comment]
I opened a new PR with changes that document Sulong's extension mechanism, which might help to decide in which direction to go: #438.

**Comment by mickjordan** [comment]
However, you decide to do this, the requirement isn't really Ruby specific, every language with a native interface is likely to need this; but evidently it is sulong specific
