### ISSUE TITLE
Suggestions for reducing the gate time

### ISSUE THREAD

**Issue by mrigger** [graalvm/sulong#525]
@grimmerm wants to reduce Sulong's gate time which currently takes around 40 minutes (3 hours if we sum up the parallel jobs). To facilitate this effort, I want to share the following analyses and recommendations:
- The textual parser is quite heavy, since it relies on Eclipse EMF and XText mechanisms which contribute most to the overall test runtime. When the bitcode parser is finished, this overhead will vanish. With it, also the redundancy of testing Sulong with the textual parser and bitcode parser will disappear. The duplicate testing time amounts around 35 minutes (see the `travis4` gate job). Finishing the bitcode parser should be our primary goal when considering the reduction of the gate time.
- One other main overhead is the use of native calls (see `ProcessUtil.executeNativeCommand`) which always start new processes. We currently use native calls to compile bitcode files (to LLVM IR `.ll` and `.bc`), to optimize them with `opt`, to assemble them and compile them to executables, and to generate the reference output. We do not cache any of these steps (one exception are the reference output files of the LLVM suite). By caching compiled bitcode files and reference results, we would be able to get rid of these native calls.
- The lower limit of the gate time is the longest running job. This has always been `travis2` with a job time of around 40 minutes. Improving other parts of the gate does not help, if we do not also reduce the runtime of this job. `travis2` only executes the GCC test cases (`mx su-tests gcc`). The test cases take a long time since they are many, but also since there are some outliers that run disproportionately long. A first step would be to identify and exclude the outliers. On the long run, we probably want to have a mechanism that allows us to split the execution of test suites. This command could look like this:
  `mx su-tests gcc 1/3` to execute the first third of the test cases, `mx su-tests gcc 2/3` to execute the second third, and so on.
- The LLVMLifeTimeAnalysisVisitor is very inefficient, and significantly adds to the gate runtime. If the bitcode parser data structures are not sufficiently more efficient, we should rewrite the visitor to use a less expensive analysis. We could also explicitly test a suite with the lifetime analysis turned on, and turn it off for other suites.
- There are some general problems of Sulong that affect the gate time. For example, loading the bitcode libraries in `mx.sulong/libs/` causes around 60% runtime overhead for a hello world program. I am not sure if this problem will be solved by the new parser, but it will likely again become a problem when we start to execute larger parts of the standard library. We could experiment with assembling all the separate files into a single `.ll` file, serialize the parts of the standard library, and/or only parse these files on demand. @chrisseaton previously suggested that the `.su` files could contain a table of the contained functions, which would be suitable to implement such a mechanism.
- Another general problem is that we do not support on-stack replacement (OSR). It is not easy to reuse the Truffle OSR mechanisms in the context of non-structured control flow. An alternative would be to use `opt`'s `-extract-blocks` pass which extracts all basic blocks into a new function. This would help to achieve peak performance faster, and probably the Truffle inlining would again inline these calls. However, I am not sure if this would actually improve the gate time.

@chrisseaton, @jkreindl, @pointhi, @lxp feel free to correct me or add your own suggestions on how you think the gate time should be improved. I think that demonstrating the current problems in the test gate performance, and suggestions to improve it will help @grimmerm to decide on how the gate and tests should be refactored/rewritten/improved.

**Comment by chrisseaton** [comment]
> The lower limit of the gate time is the longest running job. This has always been travis2 with a job time of around 40 minutes. Improving other parts of the gate does not help

In an ideal world where all our jobs start at the same time, yes. But in reality jobs stagger start as presumably they limit how many workers we can use at once, so reducing the number of time or other jobs should help as well.

**Comment by mrigger** [comment]
Yes, I agree. I just did not consider reducing jobs since it would remove test coverage. The JRuby+Truffle gate job (#521) was of course an exception since the Sulong gate should not host such integration tests.

**Comment by mrigger** [comment]
The gate time has been reduced significantly. Thus, I close the issue.
