### ISSUE TITLE
Executable linked files?

### ISSUE THREAD

**Issue by bjfish** [graalvm/sulong#531]
After running the link command:
`mx su-link -o test.su  test.ll`
Should the resulting su file be executable?
`-rw-r--r--+  1 brandonfish  staff    628 Nov  4 23:27 test.su`
I believe the output of clang after linking would be executable.

I'm looking at this for jruby+truffle mkmf usage: https://github.com/jruby/jruby/blob/6a436e9a12df1c9929d5c8c22c4025fed5adef57/lib/ruby/stdlib/mkmf.rb#L542

cc: @chrisseaton

**Comment by chrisseaton** [comment]
I'm not sure making the output files executable makes any sense - nobody needs to execute them.

I understand your problem in Ruby, but I think it's Ruby that needs to work around this. We could modify `mkmf.rb`, or we could do some kind of special case in `File.executable?`.

**Comment by bjfish** [comment]
I found a little explanation here about why these may be executable:
http://unix.stackexchange.com/questions/40587/why-are-shared-libraries-executable

**Comment by chrisseaton** [comment]
This is all irrelevant though - our `.so` files are just zip files with text data in them. We don't need them to be executable for any of the reasons described here.

However from reading that page maybe `mkmf.rb` is wrong anyway. It sounds like there isn't a requirement for them to be executable. Maybe we should ask if they'll accept the change upstream?

**Comment by bjfish** [comment]
Yes, it sounds like we should try to make a ruby mkmf change upstream and workaround this for now.  Feel free to close this issue. Thanks.
