### ISSUE TITLE
failing unittests in `SulongSuite`

### ISSUE THREAD

**Issue by rschatz** [graalvm/sulong#536]
### broken tests

- c++/simple/ignore/simpleclass --> uses uninitialized field
- c/struct/packed/packed1 --> out of bounds memory access
- c/truffle-c/variousTest/ignore/pointerTest13 --> uses uninitialized memory (malloc)

### propably real sulong issue (to be investigated)

- c/truffle-c/structTest/ignore/passPerValue2a --> seems like the struct is not passed by value
- c/truffle-c/programTest/noopt/programTest6
- c/max-unsigned-int-to-double-cast

- c/truffle-c/structTest/ignore/test001 --> something is very weird with this test, neither "expected: 145" nor "was: -1" make sense to me

- qsort --> function pointer escapes to native

### parser error
- c/truffle-c/structTest/ignore/passPerValue4
- c/truffle-c/bitFields/noopt/cornerCase2

### test harness issue

The test harness compares the posix return value of the reference program to the return value of the `main` function in sulong. In the following tests, this fails because the posix return value is truncated to a byte.

- c/truffle-c/unionTest/ignore/unionTest10
- c/truffle-c/unionTest/ignore/memberInitialization1
- c/truffle-c/unionTest/ignore/unionTest11
- c/truffle-c/unionTest/ignore/memberInitialization2a

**Comment by grimmerm** [comment]
I suggest we 
- fix broken tests
- introduce a whitelist for sulong testsuite as well (as we have for llvm tests etc) and exclude the tests that @rschatz  listed under parser error, sulong issues.
I would prefer a whitelist for sulong suite instead of giving folder names a semantic (e.g. folder name ignore). /cc @mrigger 
- also truncate sulong return value to 8 bit before comparison

Then sulong suite should pass.

**Comment by mrigger** [comment]
I think we should not automatically truncate Sulong's return value. Doing so can hide errors. Instead, we should print the value, once the stdout comparison is in place. As an alternative, we could do a comparison with the expected value, and `abort` if we do not get the expected result.

I agree with the other points. We also have to see if some of these test cases expose bugs in Sulong.

**Comment by rschatz** [comment]
If the test harness compares the return value of `main` with an exit code, it has to truncate to 8 bit. But that should be done in the test harness, not in Sulong.

But I agree with @mrigger, better would be to just not use the exit code in the test harness at all, or possibly even always expect 0 exit code, and use non-0 exit code explicitly to detect segfaults and so on...

**Comment by grimmerm** [comment]
of course, we only truncate in the test harness.
