### ISSUE TITLE
LLVMNodeGenerator does not use the LLVMBitcodeVisitor's factory facade

### ISSUE THREAD

**Issue by mrigger** [graalvm/sulong#556]
The `LLVMNodeGenerator` uses the hard-coded standard factories to create nodes. Instead, it should use the bitcode visitor's factory facade (`method.getModule().getParserRuntime().getNodeFactoryFacade()`) to instantiate the nodes. To achieve this, we have to remove the `static` modifier of some of the methods.

@jkreindl or @pointhi could you have a look at this?

**Comment by jkreindl** [comment]
I have been working on this issue since last friday. Unfortunately, I ran into the problem that our converters between Textparser and Binary Parser types did not yet support cyclic type definitions. I had to fix that before I could proceed.

**Comment by mrigger** [comment]
Solved by #562.
