### ISSUE TITLE
Test discovery and list of supported test cases

### ISSUE THREAD

**Issue by mrigger** [graalvm/sulong#584]
Initially, when running a test suite and setting `-Dsulong.Debug=true -Dsulong.TestDiscoveryPath=<path>` resulted in printing a list of passing test cases (after every executed test case). This made it easy to add newly supported test cases to an `.include` file. It would be great if we had similar functionality in the new test harness.

**Comment by grimmerm** [comment]
see https://github.com/graalvm/sulong/pull/627
