### ISSUE TITLE
Fastaredux segfault

### ISSUE THREAD

**Issue by grimmerm** [graalvm/sulong#599]
After migration to new parser, the fastaredux.gcc-2.gcc benchmark segfaults.
See TODO in ShootoutsSulongOnlySuite.java

**Comment by jkreindl** [comment]
This is not a bug in Sulong, but rather an issue with the Testcase. We actually describe this in detail at [here](https://github.com/graalvm/sulong/blob/master/docs/SAFE-SULONG.md#the-computer-language-benchmarks-game-fasta-redux-c-gcc-2-program).
