### ISSUE TITLE
Parsing speed

### ISSUE THREAD

**Issue by mickjordan** [graalvm/sulong#619]
In some cases parsing seems exceptionally slow/memory intensive. Here is a run logging GC and parsing times. Note especially the sha256 case; 57 seconds with lots of GCs. This file is 6081 lines when disassembled. This is using the Base64 encoding.

> library(digest)
[GC (Allocation Failure)  142692K->65871K(275456K), 0.0251611 secs]
[GC (Metadata GC Threshold)  95795K->68533K(278528K), 0.0255689 secs]
[Full GC (Metadata GC Threshold)  68533K->65344K(420864K), 0.5345448 secs]
parsed Rdynload_fastr_llvm in 1.985095 secs
parsed Rinternals_llvm in 0.145350 secs
parsed X11_fastr_llvm in 0.012180 secs
parsed arithmetic_fastr_llvm in 0.058646 secs
parsed caccess_llvm in 0.002622 secs
parsed coerce_fastr_llvm in 0.095801 secs
[GC (Allocation Failure)  197952K->73615K(436736K), 0.0112615 secs]
[GC (Allocation Failure)  249231K->74703K(465920K), 0.0075921 secs]
parsed dchdc_llvm in 0.986321 secs
parsed dpbfa_llvm in 0.039003 secs
parsed dpbsl_llvm in 0.024335 secs
[GC (Allocation Failure)  250831K->74871K(493056K), 0.0077524 secs]
parsed dpoco_llvm in 0.353784 secs
parsed dpodi_llvm in 0.042069 secs
parsed dpofa_llvm in 0.018333 secs
parsed dposl_llvm in 0.012927 secs
[GC (Allocation Failure)  280695K->75103K(494080K), 0.0093912 secs]
parsed dqrdc2_llvm in 0.377752 secs
[GC (Allocation Failure)  280927K->75399K(530944K), 0.0091084 secs]
parsed dqrdc_llvm in 0.367534 secs
[GC (Allocation Failure)  319111K->74714K(529920K), 0.0065138 secs]
parsed dqrls_llvm in 0.148165 secs
parsed dqrsl_llvm in 0.282973 secs
[GC (Allocation Failure)  318426K->74786K(570880K), 0.0090282 secs]
parsed dqrutl_llvm in 0.107836 secs
[GC (Allocation Failure)  362530K->82795K(571904K), 0.0157265 secs]
[GC (Allocation Failure)  370539K->84246K(622080K), 0.0142286 secs]
[GC (Allocation Failure)  422678K->84883K(622080K), 0.0143807 secs]
[GC (Allocation Failure)  423315K->85151K(663040K), 0.0140765 secs]
[GC (Allocation Failure)  464031K->85227K(663040K), 0.0120058 secs]
parsed dsvdc_llvm in 3.944762 secs
parsed dtrco_llvm in 0.183107 secs
parsed dtrsl_llvm in 0.056842 secs
parsed errors_fastr_llvm in 0.001599 secs
parsed inlined_fastr_llvm in 0.022137 secs
parsed llvm_dummy_llvm in 0.000731 secs
parsed localecharset_fastr_llvm in 0.000989 secs
parsed print_fastr_llvm in 0.004840 secs
parsed printutils_fastr_llvm in 0.008442 secs
parsed rffiutils_llvm in 0.001364 secs
parsed sys_fastr_llvm in 0.007264 secs
parsed unimplemented_llvm in 0.006537 secs
[GC (Allocation Failure)  464107K->76691K(699904K), 0.0095189 secs]
parsed util_fastr_llvm in 0.029843 secs
parsed variables_llvm in 0.010162 secs
[GC (Allocation Failure)  496531K->80337K(703488K), 0.0104291 secs]
[GC (Allocation Failure)  500177K->80553K(745984K), 0.0116386 secs]
[GC (Allocation Failure)  545449K->80840K(745472K), 0.0114344 secs]
[GC (Allocation Failure)  545736K->81095K(788480K), 0.0073050 secs]
[GC (Allocation Failure)  593607K->80465K(792576K), 0.0069022 secs]
[GC (Allocation Failure)  592977K->80973K(823296K), 0.0073309 secs]
[GC (Allocation Failure)  627277K->81271K(825856K), 0.0055067 secs]
[GC (Allocation Failure)  627575K->81523K(852992K), 0.0061861 secs]
parsed aes in 5.911964 secs
parsed crc32 in 0.166668 secs
parsed digest in 0.131962 secs
parsed init in 0.003299 secs
[GC (Allocation Failure)  658547K->81325K(855552K), 0.0050728 secs]
[GC (Allocation Failure)  658349K->81424K(884224K), 0.0055147 secs]
parsed md5 in 0.883838 secs
parsed pmurhash in 0.025096 secs
parsed raes in 0.004796 secs
[GC (Allocation Failure)  688144K->84527K(884224K), 0.0069984 secs]
[GC (Allocation Failure)  691247K->84511K(910336K), 0.0076376 secs]
[GC (Allocation Failure)  720927K->84526K(911360K), 0.0069150 secs]
[GC (Allocation Failure)  720942K->84574K(933888K), 0.0072178 secs]
[GC (Allocation Failure)  746078K->84510K(934912K), 0.0067509 secs]
[GC (Allocation Failure)  746014K->84624K(956928K), 0.0067294 secs]
[GC (Allocation Failure)  770704K->84641K(958464K), 0.0041786 secs]
[GC (Allocation Failure)  770721K->84675K(979968K), 0.0056349 secs]
[GC (Allocation Failure)  793795K->84720K(980480K), 0.0047354 secs]
parsed sha1 in 7.845819 secs
parsed sha2 in 0.153834 secs
[GC (Allocation Failure)  793840K->91309K(1001472K), 0.0118737 secs]
[GC (Allocation Failure)  821933K->91821K(1001984K), 0.0096503 secs]
[GC (Allocation Failure)  822445K->91884K(1022976K), 0.0106453 secs]
[GC (Allocation Failure)  842988K->91847K(1023488K), 0.0076999 secs]
[GC (Allocation Failure)  842951K->91871K(1044992K), 0.0101080 secs]
[GC (Allocation Failure)  864479K->91895K(1044992K), 0.0070049 secs]
[GC (Allocation Failure)  864503K->91932K(1063424K), 0.0092241 secs]
[GC (Allocation Failure)  885532K->91988K(1064448K), 0.0062310 secs]
b[GC (Allocation Failure)  885588K->91948K(1081856K), 0.0080275 secs]
[GC (Allocation Failure)  905516K->91996K(1082880K), 0.0067278 secs]
[GC (Allocation Failure)  905564K->91995K(1099776K), 0.0081483 secs]
[GC (Allocation Failure)  923995K->92020K(1100288K), 0.0064708 secs]
[GC (Allocation Failure)  924020K->92052K(1118208K), 0.0081198 secs]
[GC (Allocation Failure)  942484K->92028K(1118208K), 0.0076536 secs]
[GC (Allocation Failure)  942460K->92060K(1135104K), 0.0080525 secs]
[GC (Allocation Failure)  960924K->92068K(1135616K), 0.0091412 secs]
[GC (Allocation Failure)  960932K->92188K(1152512K), 0.0029971 secs]
[GC (Allocation Failure)  977436K->92252K(1154560K), 0.0027105 secs]
[GC (Allocation Failure)  977500K->92284K(1166848K), 0.0032126 secs]
[GC (Allocation Failure)  989820K->92316K(1167872K), 0.0031861 secs]
[GC (Allocation Failure)  989852K->92444K(1176064K), 0.0027266 secs]
[GC (Allocation Failure)  999708K->92508K(1177600K), 0.0027917 secs]
[GC (Allocation Failure)  999772K->92572K(1185280K), 0.0031230 secs]
[GC (Allocation Failure)  1008540K->92636K(1185792K), 0.0027684 secs]
[GC (Allocation Failure)  1008604K->92700K(1191424K), 0.0029107 secs]
[GC (Allocation Failure)  1016348K->92764K(1192448K), 0.0027186 secs]
[GC (Allocation Failure)  1016412K->92788K(1197056K), 0.0030072 secs]
[GC (Allocation Failure)  1023604K->92916K(1198080K), 0.0028328 secs]
[GC (Allocation Failure)  1023732K->92948K(1203712K), 0.0031987 secs]
[GC (Allocation Failure)  1030932K->93012K(1204224K), 0.0032271 secs]
[GC (Allocation Failure)  1030996K->93108K(1207808K), 0.0028438 secs]
[GC (Allocation Failure)  1037748K->93172K(1209344K), 0.0028907 secs]
[GC (Allocation Failure)  1037812K->93236K(1214464K), 0.0032255 secs]
[GC (Allocation Failure)  1044532K->93260K(1214976K), 0.0036205 secs]
[GC (Allocation Failure)  1044556K->93324K(1220096K), 0.0029499 secs]
[GC (Allocation Failure)  1051788K->93356K(1220608K), 0.0030830 secs]
[GC (Allocation Failure)  1051820K->93452K(1225216K), 0.0033402 secs]
parsed sha256 in 57.476613 secs
parsed xxhash in 0.996170 secs

**Comment by grimmerm** [comment]
Done.
