### ISSUE TITLE
Publish parser to maven

### ISSUE THREAD

**Issue by okutane** [graalvm/sulong#674]
Hello!
Thanks for the Sulong, it's really nice and I would like to use it's parser in my project. In fact I really need only it's llvm bytecode parser, so it would be nice to get it as a simple maven dependency. :) Is it possible to have such "improvement" ?

**Comment by grimmerm** [comment]
Thanks for using Sulong!
Currently there is no plan to publish Sulong's parser to maven. I'm happy to answer any Sulong related questions if you're planning to do that.
