### ISSUE TITLE
Forward reference types still not fully supported

### ISSUE THREAD

**Issue by mikehearn** [graalvm/sulong#748]
I saw a PR go in recently that said it added support for forward reference types, but the support seems incomplete.

It is possible to have bitcode that defines structs before all the member types are defined. Reading the LLVM format docs, it seems the parser is expected to use a type table. Unfortunately Sulong has that table but resolves indexes to objects as the records are read, which is too early. There's some infrastructure to try and tackle this for a few types, but it doesn't work for structs.

The fix is probably to load structs whilst parsing as an intermediate type that keeps around the indexes, then re-iterate over the type table and convert to StructureType after the parse is fully completed.

**Comment by grimmerm** [comment]
@jkreindl can you have a look pls
