### ISSUE TITLE
Eclipseformat behavior change

### ISSUE THREAD

**Issue by hackyourlife** [graalvm/sulong#758]
Eclipseformat in travis behaves differently than eclipseformat using eclipse 4.7. This results in failed travis checks like [here](https://travis-ci.org/graalvm/sulong/jobs/267937932). Right now the workaround is to download the old eclipse as defined in the travis configuration, and run eclipseformat using this eclipse version before committing changes.

**Comment by jkreindl** [comment]
As a result of this all code in the repository is forced to follow a single style guide regardless of which versions of which IDEs people are using and pull requests are not cluttered by mass changes made by a formatter. I think this is perfectly fine behavior. If you want to use formatting from within your newer eclipse I am sure you can somehow export the formatter profile from the older version.

**Comment by grimmerm** [comment]
We are using a common formatting among all projects in https://github.com/graalvm 

As @jkreindl  said, we do not want to have massive changes caused by formatters. We do not intend to change that.
