### ISSUE TITLE
Conditional Phi Write Nodes in Switch

### ISSUE THREAD

**Issue by mrigger** [graalvm/sulong#79]
Conditional phi writes occur in conditional branches of a basic block, when a successor of the basic block refers to it in a phi function.

We currently execute the phi writes conditionally in the [br](http://llvm.org/docs/LangRef.html#br-instruction) instruction, but unconditionally in the [indirectbr](http://llvm.org/docs/LangRef.html#indirectbr-instruction) and [switch](http://llvm.org/docs/LangRef.html#switch-instruction) instructions.

I am not sure whether cases can occur where this is a problem. Probably, we should extend the test suite with more complicated control flow structure tests to find out if we can break the current implementation.

**Comment by grimmerm** [comment]
We rewrote the LLVMDispatchBasicBlock node in that respect.
