### ISSUE TITLE
Catching a C++ exception hangs the process

### ISSUE THREAD

**Issue by stabbylambda** [graalvm/sulong#849]
## Description
When we try to catch a `std::runtime_error` in the C++ code, we get the following abort message printed to stderr.
```
libc++abi.dylib: Type error in sulong_eh_canCatch(…)
Syscalls (write) not supported on this OS.
Syscalls (write) not supported on this OS.
Syscalls (write) not supported on this OS.
Syscalls (write) not supported on this OS.
Syscalls (write) not supported on this OS.
Syscalls (write) not supported on this OS.
...
``` 

The Syscalls (write) portion runs forever (I know the syscalls message is because I'm on macOS. I haven't run it on a linux vm yet).

## Suspected Cause
I tracked this down to the definition of [sulong_eh_canCatch](https://github.com/graalvm/sulong/blob/5f7532e892ca25e092367d3825f05015ff2c3f7e/projects/com.oracle.truffle.llvm.libraries.bitcode/libcxxabi/cxa_exception.cpp#L706)

```cpp
unsigned int sulong_eh_canCatch(_Unwind_Exception *unwindHeader, std::type_info *catchType) {
    __cxa_exception *ex = cxa_exception_from_exception_unwind_exception(unwindHeader);
    void *p = thrown_object_from_cxa_exception(ex);
    __shim_type_info *et = dynamic_cast<__shim_type_info*>(ex->exceptionType); 
    __shim_type_info *ct = dynamic_cast<__shim_type_info*>(catchType);
    if (et == NULL || ct == NULL) { 
        abort_message("Type error in sulong_eh_canCatch(...).\n");
    }
    if (ct->can_catch(et, p)) {
        ex->adjustedPtr = p;
        return 1;
    } else {
        return 0;
    }
}
```

In the case that the C++ code throws a `std::runtime_error`, `ex->exceptionType` is an `St13runtime_error` and `et` becomes null. The exception never gets marshalled over into the Java code that I’ve got, so I’m unable to catch the error.
I would have expected it to get wrapped in a RuntimeException so that I could handle it.

## Reproduction steps
I've created what I believe to be the minimal testcase here: https://github.com/stabbylambda/sulongexceptiontest

**Comment by stabbylambda** [comment]
@mrigger I brought this up in the graalvm gitter and @smarr said you would probably be the right person to talk to about this.

**Comment by mrigger** [comment]
Thank you for reporting this issue! @rschatz worked on the implementation of exception support, so I think that he can help you further.

**Comment by rschatz** [comment]
Thanks for the detailed bug report and repro-case.

The problem with not being able to catch the exception was that we were missing some of the standard exceptions in our internal `libc++abi` library. Your code picked up the native version of `std::runtime_error`, which is incompatible.

Should be fixed in current master (https://github.com/graalvm/sulong/commit/4b06d68a3269525befdcdf53367c454976df5ef4), and will probably be included in RC3.

The infinite loop is a different issue, and seems to be mac specific. I still have to investigate that.

**Comment by rschatz** [comment]
The infinite loop was just a confusion of syscall numbers between mac and linux (on mac, "exit" has syscall number 1, on linux number 1 is "write"). Should be fixed as well.

**Comment by stabbylambda** [comment]
@rschatz Awesome. Thanks!
