### ISSUE TITLE
How to pass native arrays of primitive types into other polyglot languages

### ISSUE THREAD

**Issue by markehammons** [graalvm/sulong#861]
In the reference documentation for llvm on the polyglot engine, you have a macro and methods demonstrated to pass native arrays of structs into other languages:

``` 
POLYGLOT_DECLARE_STRUCT(Point)
void *allocNativePointArray(int length) {
    struct Point *ret = calloc(length, sizeof(*ret));
    return polyglot_from_Point_array(ret, length);
}
```

However, when I look at polyglot.h, there doesn't appear to be any similar methods for the primitive types. How would one do the same as above, but for a ```double*``` instead?

**Comment by jkreindl** [comment]
You don't need to call anything for primitive types. `POLYGLOT_DECLARE_STRUCT` enables other languages to read/write named members of values of the given type. This would be pointless for primitives since they do not have members.

**Comment by markehammons** [comment]
I have tried to use native arrays and couldn't get it to work. Could you post some example code of getting a native array in java and accessing it's members?

**Comment by jkreindl** [comment]
I'm sorry, I misunderstood your question. I thought you wanted a function that lets you export primitive values to other languages, which is indeed unnecessary. I am not aware of any function that lets you declare an array length for a primitive array either. @rschatz Can you answer this?

**Comment by rschatz** [comment]
Fixed in master (https://github.com/graalvm/sulong/commit/a72ce59f1228615acace072cd2ac356534dd332a), should land in the next release.

There are now `polyglot_as_*_array` and `polyglot_from_*_array` functions pre-declared in `polyglot.h`.

**Comment by markehammons** [comment]
Great, glad to hear it!
