### ISSUE TITLE
Lookup of Native Functions with Exceeding Polymorphic Inline Cache Limit

### ISSUE THREAD

**Issue by mrigger** [graalvm/sulong#91]
When we have an indirect call in Sulong which exceeds the polymorphic inline cache limit we perform the function lookup every time. This is not a problem for Truffle functions but for native functions: Whenever we get a native handle we also install the call stub for it which eventually results in a bailout exception. To circumvent this problem we currently have [a cache for native function lookups](https://github.com/graalvm/sulong/commit/4a8fbdd680ac9b3b9e8fafa789e4eda4097be058). There are also other deficiencies in the current implementation, since we create the call target every time in this case.

To efficiently support indirect calls with native targets it would be nice if we could extend the Graal Native Function Interface to be able to specify the parameters beforehand, and then pass the function pointer as one of the arguments.

**Comment by grimmerm** [comment]
We are not using the Graal Native Function Interface anymore.
